export const LANGUAGES = [
    { code: 'en', name: 'English', dir: 'ltr' },
    { code: 'ar', name: 'العربية', dir: 'rtl' },
    { code: 'hi', name: 'हिन्दी', dir: 'ltr' },
    { code: 'ur', name: 'اردو', dir: 'rtl' },
    { code: 'bn', name: 'বাংলা', dir: 'ltr' },
    { code: 'tl', name: 'Tagalog', dir: 'ltr' },
    { code: 'ne', name: 'नेपाली', dir: 'ltr' },
    { code: 'ml', name: 'മലയാളം', dir: 'ltr' },
    { code: 'ta', name: 'தமிழ்', dir: 'ltr' },
    { code: 'te', name: 'తెలుగు', dir: 'ltr' },
    { code: 'kn', name: 'ಕನ್ನಡ', dir: 'ltr' },
    { code: 'or', name: 'ଓଡ଼ିଆ', dir: 'ltr' },
    { code: 'si', name: 'සිංහල', dir: 'ltr' },
    { code: 'ps', name: 'پښتو', dir: 'rtl' },
    { code: 'ro', name: 'Română', dir: 'ltr' },
    { code: 'zh', name: '中文', dir: 'ltr' },
    { code: 'sw', name: 'Kiswahili', dir: 'ltr' }
] as const;

export type LanguageCode = typeof LANGUAGES[number]['code'];

export const translations: Record<string, Record<string, string>> = {
    /* ================= ENGLISH ================= */
    en: {
        // Shared
        welcome: 'WELCOME BACK',
        safetyAlert: 'Please send a copy of your Swipe Card / Employee ID to this number on WhatsApp.',
        profile: 'USER PROFILE',
        langLabel: 'Language',
        logout: 'LOG OUT',

        // Login Page
        login: 'LOGIN',
        signup: 'SIGN UP',
        empNum: 'Employee Number',
        empName: 'Name',
        mobile: 'Mobile Number',
        depot: 'Depot',
        pass: 'Password',
        confirmPass: 'Confirm Password',
        forgot: 'Forgot Password?',
        btnLogin: 'START TRAINING',
        btnSignup: 'CREATE ACCOUNT',
        error: 'INVALID CREDENTIALS',

        // Password Change
        changePassLink: 'Change Password',
        oldPass: 'Old Password',
        newPass: 'New Password',
        rePass: 'Re-Enter New Password',
        btnChange: 'CHANGE',
        btnBack: 'BACK',
        passSuccess: 'Password Updated Successfully',
        passError: 'Error: Check Old Password',
        passMismatch: 'New passwords do not match',

        // Dashboard & Player
        pending: 'PENDING TASKS',
        completed: 'COMPLETED UNITS',
        training: 'Training',
        assessment: 'Assessment',
        score: 'Score',
        completedDate: 'Validated on:',
        next: 'NEXT',
        prev: 'PREVIOUS',
        finish: 'FINISH MODULE',

        // Loading States (NEW)
        loadingTraining: 'LOADING TRAINING...',
        loadingTest: 'LOADING TEST...',
        ready: 'READY',

        // NEW KEYS (Login & Instructions)
        lblId: 'Employee ID / QID',
        instrTitle: 'Instructions:',
        instrStaffTitle: 'Mowasalat Staff:',
        instrStaffText: 'Enter Staff No / Employee ID',
        instrOthersTitle: 'Others:',
        instrOthersText: 'Enter QID, Passport No, or Visa No',
        phCompany: 'Company',
        companyInstr: 'Please enter the name of your company.',
        phDesignation: 'Designation / Team',
        phDepot: 'Select Location',
        phAssignedLocation: 'Assigned Location',
        phCustomDesignation: 'Enter Designation / Team',
        alertAccountCreated: 'Account Created! Please Login.',
        errMissingFields: 'Please fill in all required fields.',
        errPassMismatch: 'Passwords do not match.',
        errRegistrationFailed: 'Registration failed', // Fallback
        btnWait: 'Please wait...',
        phEmail: 'Email Address',
        phAssignedArea: 'Assigned Area',
        phSelectCompany: 'Select Company',
        phOthersSpecify: 'Others (Specify)',
        phEnterCompanyName: 'Enter Company Name',

        // New Audited Keys (Internationalization)
        selectLanguage: 'SELECT LANGUAGE',
        languageSelection: 'Language Selection',
        selectLanguageToContinue: 'Please select a language to continue',
        secureConnection: 'Secure Connection',
        loginSuccessful: 'Login Successful',
        redirecting: 'Redirecting...',
        plzLoginDashboard: 'Please login to access your dashboard',
        cancel: 'Cancel',
        contactSupport: 'Contact Support',
        hsseModules: 'Training Modules',
        noPendingTraining: 'No pending training',
        noCompletedHistory: 'No completed history',
        inProgress: 'In Progress',
        notStarted: 'Not Started',
        attemptFailed: 'Attempt Failed',
        edit: 'Edit',
        signOut: 'Sign Out',
        update: 'Update',
        saving: 'Saving...',
        updating: 'Updating...',
        welcomeDashboard: 'Welcome to your Training Dashboard'
    },

    /* ================= CHINESE (Simplified) ================= */
    zh: {
        // Shared
        welcome: '欢迎回来',
        safetyAlert: '请确保出发前已佩戴所有必需的 PPE。',
        profile: '用户资料',
        langLabel: '语言',
        logout: '登出',
        // Login Page
        login: '登录',
        signup: '注册',
        empNum: '员工编号',
        empName: '姓名',
        mobile: '手机号码',
        depot: '车厂',
        pass: '密码',
        confirmPass: '确认密码',
        forgot: '忘记密码？',
        btnLogin: '开始培训',
        btnSignup: '创建账户',
        error: '凭据无效',

        // Password Change
        changePassLink: '更改密码',
        oldPass: '旧密码',
        newPass: '新密码',
        rePass: '重新输入新密码',
        btnChange: '更改',
        btnBack: '返回',
        passSuccess: '密码更新成功',
        passError: '错误：检查旧密码',
        passMismatch: '新密码不匹配',

        // Dashboard & Player
        pending: '待办事宜',
        completed: '已完成模块',
        training: '培训',
        assessment: '评估',
        score: '分数',
        completedDate: '验证日期：',
        next: '下一步',
        prev: '上一步',
        finish: '完成模块',

        // Loading States
        loadingTraining: '加载培训中...',
        loadingTest: '加载测试中...',
        ready: '准备就绪',

        // NEW KEYS
        lblId: '员工 ID / 卡塔尔 ID',
        instrTitle: '说明：',
        instrStaffTitle: 'Mowasalat 员工：',
        instrStaffText: '输入员工编号 / 员工 ID',
        instrOthersTitle: '其他：',
        instrOthersText: '输入卡塔尔 ID、护照号或签证号',
        phCompany: '公司',
        companyInstr: '请输入您的公司名称。',
        phDesignation: '职位 / 团队',
        phDepot: '选择地点',
        phAssignedLocation: '指定地点',
        phCustomDesignation: '输入职位 / 团队',
        alertAccountCreated: '账户已创建！请登录。',
        errMissingFields: '请填写所有必填字段。',
        errPassMismatch: '密码不匹配。',
        errRegistrationFailed: '注册失败',
        btnWait: '请稍候...',
        phEmail: '电子邮件地址',
        phAssignedArea: '指定区域',
        phSelectCompany: '选择公司',
        phOthersSpecify: '其他（请注明）',
        phEnterCompanyName: '输入公司名称',

        // New Audited Keys (Internationalization)
        selectLanguage: '选择语言',
        languageSelection: '语言选择',
        selectLanguageToContinue: '请选择语言以继续',
        secureConnection: '安全连接',
        loginSuccessful: '登录成功',
        redirecting: '正在重定向...',
        plzLoginDashboard: '请登录以访问您的控制面板',
        cancel: '取消',
        contactSupport: '联系支持',
        hsseModules: '培训模块',
        noPendingTraining: '无待办培训',
        noCompletedHistory: '无已完成历史',
        inProgress: '进行中',
        notStarted: '未开始',
        attemptFailed: '尝试失败',
        edit: '编辑',
        signOut: '退出登录',
        update: '更新',
        saving: '正在保存...',
        updating: '正在更新...',
        welcomeDashboard: '欢迎来到您的培训仪表板'
    },

    /* ================= SWAHILI ================= */
    sw: {
        // Shared
        welcome: 'Karibu Tena',
        safetyAlert: 'Tafadhali hakikisha umevaa PPE zote zinazohitajika kabla ya kuondoka.',
        profile: 'Wasifu wa Mtumiaji',
        langLabel: 'Lugha',
        logout: 'Toka',
        // Login Page
        login: 'Ingia',
        signup: 'Jisajili',
        empNum: 'Nambari ya Mfanyakazi',
        empName: 'Jina',
        mobile: 'Nambari ya Simu',
        depot: 'Depo',
        pass: 'Nenosiri',
        confirmPass: 'Thibitisha Nenosiri',
        forgot: 'Umesahau Nenosiri?',
        btnLogin: 'ANZA MAFUNZO',
        btnSignup: 'TENGENEZA AKAUNTI',
        error: 'TAARIFA BATILI',

        // Password Change
        changePassLink: 'Badilisha Nenosiri',
        oldPass: 'Nenosiri la Zamani',
        newPass: 'Nenosiri Jipya',
        rePass: 'Ingiza Tena Nenosiri Jipya',
        btnChange: 'BADILISHA',
        btnBack: 'NYUMA',
        passSuccess: 'Nenosiri Limesasishwa Kikamilifu',
        passError: 'Hitilafu: Angalia Nenosiri la Zamani',
        passMismatch: 'Nenosiri mpya haziendani',

        // Dashboard & Player
        pending: 'KAZI ZINAZOSUBIRI',
        completed: 'MODULI ZILIZOKAMILIKA',
        training: 'Mafunzo',
        assessment: 'Tathmini',
        score: 'Alama',
        completedDate: 'Imethibitishwa tarehe:',
        next: 'INAYOFUATA',
        prev: 'ILIYOPITA',
        finish: 'MALIZA MODULI',

        // Loading States
        loadingTraining: 'INAPAKIA MAFUNZO...',
        loadingTest: 'INAPAKIA JARIBIO...',
        ready: 'TAYARI',

        // NEW KEYS
        lblId: 'Kitambulisho cha Mfanyakazi / QID',
        instrTitle: 'Maagizo:',
        instrStaffTitle: 'Wafanyakazi wa Mowasalat:',
        instrStaffText: 'Ingiza Nambari ya Mfanyakazi / ID',
        instrOthersTitle: 'Wengine:',
        instrOthersText: 'Ingiza QID, Nambari ya Pasipoti, au Visa',
        phCompany: 'Kampuni',
        companyInstr: 'Tafadhali ingiza jina la kampuni yako.',
        phDesignation: 'Cheo / Timu',
        phDepot: 'Chagua Eneo',
        phAssignedLocation: 'Eneo Lililopangiwa',
        phCustomDesignation: 'Ingiza Cheo / Timu',
        alertAccountCreated: 'Akaunti Imetengenezwa! Tafadhali Ingia.',
        errMissingFields: 'Tafadhali jaza sehemu zote zinazohitajika.',
        errPassMismatch: 'Nenosiri haziendani.',
        errRegistrationFailed: 'Usajili umeshindikana',
        btnWait: 'Tafadhali subiri...',
        phEmail: 'Barua pepe',
        phAssignedArea: 'Eneo Lililopangiwa',
        phSelectCompany: 'Chagua Kampuni',
        phOthersSpecify: 'Wengine (Bainisha)',
        phEnterCompanyName: 'Ingiza Jina la Kampuni',

        // New Audited Keys (Internationalization)
        selectLanguage: 'CHAGUA LUGHA',
        languageSelection: 'Uteuzi wa Lugha',
        selectLanguageToContinue: 'Tafadhali chagua lugha ili uendelee',
        secureConnection: 'Uunganisho Salama',
        loginSuccessful: 'Ingia kwa Mafanikio',
        redirecting: 'Inaelekeza...',
        plzLoginDashboard: 'Tafadhali ingia ili ufikie dashibodi yako',
        cancel: 'Ghairi',
        contactSupport: 'Wasiliana na Huduma',
        hsseModules: 'Moduli za Mafunzo',
        noPendingTraining: 'Hakuna mafunzo yanayosubiri',
        noCompletedHistory: 'Hakuna historia iliyokamilika',
        inProgress: 'Inaendelea',
        notStarted: 'Haijaanza',
        attemptFailed: 'Jaribio Limeshindwa',
        edit: 'Hariri',
        signOut: 'Toka',
        update: 'Sasisha',
        saving: 'Inahifadhi...',
        updating: 'Inasasisha...',
        welcomeDashboard: 'Karibu kwenye Dashibodi yako ya Mafunzo'
    },

    /* ================= ARABIC ================= */
    ar: {
        // Shared
        welcome: 'مرحباً بعودتك',
        safetyAlert: 'تنبيه السلامة: يُرجى التأكد من ارتداء جميع معدات الوقاية الشخصية المطلوبة قبل الانطلاق',
        profile: 'الملف الشخصي',
        langLabel: 'اللغة',
        logout: 'تسجيل الخروج',

        // Login Page
        login: 'تسجيل الدخول',
        signup: 'تسجيل جديد',
        empNum: 'رقم الموظف',
        empName: 'الاسم',
        mobile: 'رقم الجوال',
        depot: 'المستودع',
        pass: 'كلمة المرور',
        confirmPass: 'تأكيد كلمة المرور',
        forgot: 'نسيت كلمة المرور؟',
        btnLogin: 'بدء التدريب',
        btnSignup: 'إنشاء حساب',
        error: 'بيانات الدخول غير صحيحة',

        // Password Change
        changePassLink: 'تغيير كلمة المرور',
        oldPass: 'كلمة المرور القديمة',
        newPass: 'كلمة المرور الجديدة',
        rePass: 'إعادة إدخال كلمة المرور الجديدة',
        btnChange: 'تغيير',
        btnBack: 'رجوع',
        passSuccess: 'تم تحديث كلمة المرور بنجاح',
        passError: 'خطأ: تأكد من كلمة المرور القديمة',
        passMismatch: 'كلمات المرور الجديدة غير متطابقة',

        // Dashboard & Player
        pending: 'المهام المعلقة',
        completed: 'الوحدات المكتملة',
        training: 'تدريب',
        assessment: 'تقييم',
        score: 'النتيجة',
        completedDate: 'تم التحقق في:',
        next: 'التالي',
        prev: 'السابق',
        finish: 'إنهاء الوحدة',

        // Loading States (NEW)
        loadingTraining: 'جاري تحميل التدريب...',
        loadingTest: 'جاري تحميل الاختبار...',
        ready: 'جاهز',

        // NEW KEYS (Login & Instructions)
        lblId: 'رقم الموظف / رقم الهوية القطرية',
        instrTitle: 'التعليمات:',
        instrStaffTitle: 'موظفو مواصلات:',
        instrStaffText: 'أدخل رقم الموظف / رقم الهوية الوظيفية',
        instrOthersTitle: 'الآخرون:',
        instrOthersText: 'أدخل رقم الهوية القطرية أو رقم الجواز أو رقم التأشيرة',
        phCompany: 'الشركة',
        companyInstr: 'يرجى إدخال اسم شركتك.',
        phDesignation: 'المسمّى الوظيفي / الفريق',
        phDepot: 'اختر الموقع',
        phCustomDesignation: 'أدخل المسمّى الوظيفي / الفريق',
        alertAccountCreated: 'تم إنشاء الحساب! يرجى تسجيل الدخول.',
        errMissingFields: 'يرجى تعبئة جميع الحقول المطلوبة.',
        errPassMismatch: 'كلمتا المرور غير متطابقتين.',
        errRegistrationFailed: 'فشل التسجيل', // Fallback
        btnWait: 'انتظر...',
        phEmail: 'عنوان البريد الإلكتروني',
        phAssignedArea: 'المنطقة المخصصة',
        phSelectCompany: 'اختر الشركة',
        phOthersSpecify: 'آخر (حدد)',
        phEnterCompanyName: 'أدخل اسم الشركة',

        // New Audited Keys (Internationalization)
        selectLanguage: 'اختر اللغة',
        languageSelection: 'اختيار اللغة',
        selectLanguageToContinue: 'يرجى اختيار اللغة للمتابعة',
        secureConnection: 'اتصال آمن',
        loginSuccessful: 'تم تسجيل الدخول بنجاح',
        redirecting: 'جاري التحويل...',
        plzLoginDashboard: 'يرجى تسجيل الدخول للوصول إلى لوحة التحكم الخاصة بك',
        cancel: 'إلغاء',
        contactSupport: 'اتصل بالدعم',
        hsseModules: 'وحدات التدريب',
        noPendingTraining: 'لا توجد تدريبات معلقة',
        noCompletedHistory: 'لا يوجد سجل مكتمل',
        inProgress: 'قيد التنفيذ',
        notStarted: 'لم يبدأ',
        attemptFailed: 'فشلت المحاولة',
        edit: 'تعديل',
        signOut: 'تسجيل الخروج',
        update: 'تحديث',
        saving: 'جاري الحفظ...',
        updating: 'جاري التحديث...',
        welcomeDashboard: 'مرحبًا بك في لوحة معلومات التدريب الخاصة بك'
    },

    /* ================= HINDI ================= */
    hi: {
        // Shared
        welcome: 'पुनः स्वागत है',
        safetyAlert: 'सुरक्षा चेतावनी: प्रस्थान से पहले सभी आवश्यक पीपीई पहनना सुनिश्चित करें',
        profile: 'उपयोगकर्ता प्रोफ़ाइल',
        langLabel: 'भाषा',
        logout: 'लॉग आउट',
        // Login Page
        login: 'लॉग इन',
        signup: 'पंजीकरण',
        empNum: 'कर्मचारी संख्या',
        empName: 'नाम',
        mobile: 'मोबाइल नंबर',
        depot: 'डिपो',
        pass: 'पासवर्ड',
        confirmPass: 'पासवर्ड की पुष्टि करें',
        forgot: 'पासवर्ड भूल गए?',
        btnLogin: 'प्रशिक्षण शुरू करें',
        btnSignup: 'खाता बनाएं',
        error: 'गलत जानकारी',
        // Password Change
        changePassLink: 'पासवर्ड बदलें',
        oldPass: 'पुराना पासवर्ड',
        newPass: 'नया पासवर्ड',
        rePass: 'नया पासवर्ड फिर से दर्ज करें',
        btnChange: 'बदलें',
        btnBack: 'वापस',
        passSuccess: 'पासवर्ड सफलतापूर्वक अपडेट हो गया',
        passError: 'त्रुटि: पुराना पासवर्ड जांचें',
        passMismatch: 'नए पासवर्ड मेल नहीं खाते',
        // Dashboard & Player
        pending: 'लंबित कार्य',
        completed: 'पूर्ण किए गए मॉड्यूल',
        training: 'प्रशिक्षण',
        assessment: 'मूल्यांकन',
        score: 'स्कोर',
        completedDate: 'सत्यापित तिथि:',
        next: 'अगला',
        prev: 'पिछला',
        finish: 'मॉड्यूल समाप्त करें',
        // Loading States (NEW)
        loadingTraining: 'प्रशिक्षण लोड हो रहा है...',
        loadingTest: 'परीक्षा लोड हो रही है...',
        ready: 'तैयार',
        // NEW KEYS (Login & Instructions)
        lblId: 'कर्मचारी आईडी / क़तर आईडी',
        instrTitle: 'निर्देश:',
        instrStaffTitle: 'मवासलात स्टाफ:',
        instrStaffText: 'स्टाफ नंबर / कर्मचारी आईडी दर्ज करें',
        instrOthersTitle: 'अन्य:',
        instrOthersText: 'क़तर आईडी, पासपोर्ट नंबर, या वीज़ा नंबर दर्ज करें',
        phCompany: 'कंपनी',
        companyInstr: 'कृपया अपनी कंपनी का नाम दर्ज करें।',
        phDesignation: 'पद / टीम',
        phDepot: 'स्थान चुनें',
        phCustomDesignation: 'पद / टीम दर्ज करें',
        alertAccountCreated: 'खाता बन गया! कृपया लॉग इन करें।',
        errMissingFields: 'कृपया सभी आवश्यक फ़ील्ड भरें।',
        errPassMismatch: 'पासवर्ड मेल नहीं खाते।',
        errRegistrationFailed: 'पंजीकरण विफल', // Fallback
        btnWait: 'कृपया प्रतीक्षा करें...',
        phEmail: 'ईमेल पता',
        phAssignedArea: 'निर्धारित क्षेत्र',
        phSelectCompany: 'कंपनी चुनें',
        phOthersSpecify: 'अन्य (निर्दिष्ट करें)',
        phEnterCompanyName: 'कंपनी का नाम दर्ज करें',

        // New Audited Keys (Internationalization)
        selectLanguage: 'भाषा चुनें',
        languageSelection: 'भाषा चयन',
        selectLanguageToContinue: 'आगे बढ़ने के लिए कृपया एक भाषा चुनें',
        secureConnection: 'सुरक्षित कनेक्शन',
        loginSuccessful: 'लॉगिन सफल',
        redirecting: 'पुनर्निर्देशित किया जा रहा है...',
        plzLoginDashboard: 'अपने डैशबोर्ड तक पहुंचने के लिए कृपया लॉगिन करें',
        cancel: 'रद्द करें',
        contactSupport: 'सहायता से संपर्क करें',
        hsseModules: 'प्रशिक्षण मॉड्यूल',
        noPendingTraining: 'कोई लंबित प्रशिक्षण नहीं',
        noCompletedHistory: 'कोई पूर्ण इतिहास नहीं',
        inProgress: 'प्रगति में है',
        notStarted: 'शुरू नहीं हुआ',
        attemptFailed: 'प्रयास विफल रहा',
        edit: 'संपादित करें',
        signOut: 'साइन आउट',
        update: 'अद्यतन करें',
        saving: 'सहेज रहा है...',
        updating: 'अद्यतन कर रहा है...',
        welcomeDashboard: 'आपके प्रशिक्षण डैशबोर्ड में आपका स्वागत है'
    },

    /* ================= URDU ================= */
    ur: {
        // Shared
        welcome: 'دوبارہ خوش آمدید',
        safetyAlert: 'حفاظتی انتباہ: روانگی سے پہلے تمام مطلوبہ PPE پہننا یقینی بنائیں',
        profile: 'صارف کی پروفائل',
        langLabel: 'زبان',
        logout: 'لاگ آؤٹ',
        // Login Page
        login: 'لاگ اِن',
        signup: 'رجسٹریشن',
        empNum: 'ملازم نمبر',
        empName: 'نام',
        mobile: 'موبائل نمبر',
        depot: 'ڈپو',
        pass: 'پاس ورڈ',
        confirmPass: 'پاس ورڈ کی تصدیق',
        forgot: 'پاس ورڈ بھول گئے؟',
        btnLogin: 'ٹریننگ شروع کریں',
        btnSignup: 'اکاؤنٹ بنائیں',
        error: 'غلط معلومات',
        // Password Change
        changePassLink: 'پاس ورڈ تبدیل کریں',
        oldPass: 'پرانا پاس ورڈ',
        newPass: 'نیا پاس ورڈ',
        rePass: 'نیا پاس ورڈ دوبارہ درج کریں',
        btnChange: 'تبدیل کریں',
        btnBack: 'واپس',
        passSuccess: 'پاس ورڈ کامیابی سے اپڈیٹ ہو گیا',
        passError: 'خرابی: پرانا پاس ورڈ چیک کریں',
        passMismatch: 'نئے پاس ورڈ آپس میں نہیں ملتے',
        // Dashboard & Player
        pending: 'زیرِ التواء کام',
        completed: 'مکمل شدہ ماڈیولز',
        training: 'تربیت',
        assessment: 'جائزہ',
        score: 'اسکور',
        completedDate: 'تصدیق کی تاریخ:',
        next: 'اگلا',
        prev: 'پچھلا',
        finish: 'ماڈیول مکمل کریں',
        // Loading States (NEW)
        loadingTraining: 'ٹریننگ لوڈ ہو رہی ہے...',
        loadingTest: 'ٹیسٹ لوڈ ہو رہا ہے...',
        ready: 'تیار',
        // NEW KEYS (Login & Instructions)
        lblId: 'ملازم آئی ڈی / قطر آئی ڈی',
        instrTitle: 'ہدایات:',
        instrStaffTitle: 'مواصلات اسٹاف:',
        instrStaffText: 'اسٹاف نمبر / ملازم آئی ڈی درج کریں',
        instrOthersTitle: 'دیگر:',
        instrOthersText: 'قطر آئی ڈی، پاسپورٹ نمبر، یا ویزا نمبر درج کریں',
        phCompany: 'کمپنی',
        companyInstr: 'براہِ کرم اپنی کمپنی کا نام درج کریں۔',
        phDesignation: 'عہدہ / ٹیم',
        phDepot: 'مقام منتخب کریں',
        phCustomDesignation: 'عہدہ / ٹیم درج کریں',
        alertAccountCreated: 'اکاؤنٹ بن گیا! براہِ کرم لاگ اِن کریں۔',
        errMissingFields: 'براہِ کرم تمام ضروری خانے پُر کریں۔',
        errPassMismatch: 'پاس ورڈ آپس میں نہیں ملتے۔',
        errRegistrationFailed: 'رجسٹریشن ناکام', // Fallback
        btnWait: 'انتظار کریں...',
        phEmail: 'ای میل ایڈریس',
        phAssignedArea: 'نامزد علاقہ',
        phSelectCompany: 'کمپنی منتخب کریں',
        phOthersSpecify: 'دیگر (وضاحت کریں)',
        phEnterCompanyName: 'کمپنی کا نام درج کریں',

        // New Audited Keys (Internationalization)
        selectLanguage: 'زبان منتخب کریں',
        languageSelection: 'زبان کا انتخاب',
        selectLanguageToContinue: 'جاری رکھنے کے لیے براہِ کرم ایک زبان منتخب کریں',
        secureConnection: 'محفوظ کنکشن',
        loginSuccessful: 'لاگ اِن کامیاب',
        redirecting: 'دوبارہ بھیجا جا رہا ہے...',
        plzLoginDashboard: 'اپنے ڈیش بورڈ تک رسائی کے لیے براہِ کرم لاگ اِن کریں',
        cancel: 'منسوخ کریں',
        contactSupport: 'سپورٹ سے رابطہ کریں',
        hsseModules: 'تربیتی ماڈیولز',
        noPendingTraining: 'کوئی زیرِ التواء تربیت نہیں',
        noCompletedHistory: 'مکمل شدہ ریکارڈ نہیں ہے',
        inProgress: 'جاری ہے',
        notStarted: 'شروع نہیں ہوا',
        attemptFailed: 'کوشش ناکام رہی',
        edit: 'ترمیم کریں',
        signOut: 'سائن آؤٹ',
        update: 'اپ ڈیٹ کریں',
        saving: 'محفوظ ہو رہا ہے...',
        updating: 'اپ ڈیٹ ہو رہا ہے...',
        welcomeDashboard: 'آپ کے ٹریننگ ڈیش بورڈ میں خوش آمدید'
    },

    /* ================= BENGALI ================= */
    bn: {
        // Shared
        welcome: 'আবার স্বাগতম',
        safetyAlert: 'নিরাপত্তা সতর্কতা: যাত্রার আগে সমস্ত প্রয়োজনীয় পিপিই পরিধান নিশ্চিত করুন',
        profile: 'ব্যবহারকারীর প্রোফাইল',
        langLabel: 'ভাষা',
        logout: 'লগ আউট',
        // Login Page
        login: 'লগইন',
        signup: 'নিবন্ধন',
        empNum: 'কর্মচারী নম্বর',
        empName: 'নাম',
        mobile: 'মোবাইল নম্বর',
        depot: 'ডিপো',
        pass: 'পাসওয়ার্ড',
        confirmPass: 'পাসওয়ার্ড নিশ্চিত করুন',
        forgot: 'পাসওয়ার্ড ভুলে গেছেন?',
        btnLogin: 'প্রশিক্ষণ শুরু করুন',
        btnSignup: 'অ্যাকাউন্ট তৈরি করুন',
        error: 'ভুল তথ্য',
        // Password Change
        changePassLink: 'পাসওয়ার্ড পরিবর্তন করুন',
        oldPass: 'পুরনো পাসওয়ার্ড',
        newPass: 'নতুন পাসওয়ার্ড',
        rePass: 'নতুন পাসওয়ার্ড আবার লিখুন',
        btnChange: 'পরিবর্তন',
        btnBack: 'ফিরে যান',
        passSuccess: 'পাসওয়ার্ড সফলভাবে আপডেট হয়েছে',
        passError: 'ত্রুটি: পুরনো পাসওয়ার্ড যাচাই করুন',
        passMismatch: 'নতুন পাসওয়ার্ড মিলছে না',
        // Dashboard & Player
        pending: 'মুলতবি কাজ',
        completed: 'সম্পন্ন মডিউল',
        training: 'প্রশিক্ষণ',
        assessment: 'মূল্যায়ন',
        score: 'স্কোর',
        completedDate: 'যাচাইয়ের তারিখ:',
        next: 'পরবর্তী',
        prev: 'পূর্ববর্তী',
        finish: 'মডিউল সম্পন্ন করুন',
        // Loading States (NEW)
        loadingTraining: 'প্রশিক্ষণ লোড হচ্ছে...',
        loadingTest: 'পরীক্ষা লোড হচ্ছে...',
        ready: 'প্রস্তুত',
        // NEW KEYS (Login & Instructions)
        lblId: 'কর্মচারী আইডি / কাতার আইডি',
        instrTitle: 'নির্দেশাবলী:',
        instrStaffTitle: 'মওয়াসালাত স্টাফ:',
        instrStaffText: 'স্টাফ নম্বর / কর্মচারী আইডি লিখুন',
        instrOthersTitle: 'অন্যান্য:',
        instrOthersText: 'কাতার আইডি, পাসপোর্ট নম্বর, বা ভিসা নম্বর লিখুন',
        phCompany: 'কোম্পানি',
        companyInstr: 'অনুগ্রহ করে আপনার কোম্পানির নাম লিখুন।',
        phDesignation: 'পদবি / টিম',
        phDepot: 'লোকেশন নির্বাচন করুন',
        phCustomDesignation: 'পদবি / টিম লিখুন',
        alertAccountCreated: 'অ্যাকাউন্ট তৈরি হয়েছে! অনুগ্রহ করে লগইন করুন।',
        errMissingFields: 'অনুগ্রহ করে সব প্রয়োজনীয় তথ্য পূরণ করুন।',
        errPassMismatch: 'পাসওয়ার্ড মিলছে না।',
        errRegistrationFailed: 'নিবন্ধন ব্যর্থ হয়েছে', // Fallback
        btnWait: 'অপেক্ষা করুন...',
        phEmail: 'ইমেল ঠিকানা',
        phAssignedArea: 'বরাদ্দ এলাকা',
        phSelectCompany: 'কোম্পানি নির্বাচন করুন',
        phOthersSpecify: 'অন্যান্য (উল্লেখ করুন)',
        phEnterCompanyName: 'কোম্পানির নাম লিখুন',

        // New Audited Keys (Internationalization)
        selectLanguage: 'ভাষা নির্বাচন করুন',
        languageSelection: 'ভাষা বাছাই',
        selectLanguageToContinue: 'এগিয়ে যেতে দয়া করে একটি ভাষা নির্বাচন করুন',
        secureConnection: 'নিরাপদ সংযোগ',
        loginSuccessful: 'লগইন সফল',
        redirecting: 'পুননির্দেশিত করা হচ্ছে...',
        plzLoginDashboard: 'আপনার ড্যাশবোর্ড ব্যবহার করতে দয়া করে লগইন করুন',
        cancel: 'বাতিল',
        contactSupport: 'সহায়তার জন্য যোগাযোগ করুন',
        hsseModules: 'প্রশিক্ষণ মডিউল',
        noPendingTraining: 'কোনো মুলতবি প্রশিক্ষণ নেই',
        noCompletedHistory: 'কোনো সম্পন্ন ইতিহাস নেই',
        inProgress: 'চলমান',
        notStarted: 'শুরু হয়নি',
        attemptFailed: 'প্রচেষ্টা ব্যর্থ হয়েছে',
        edit: 'সম্পাদনা',
        signOut: 'সাইন আউট',
        update: 'আপডেট করুন',
        saving: 'সংরক্ষণ করা হচ্ছে...',
        updating: 'আপডেট করা হচ্ছে...',
        welcomeDashboard: 'আপনার প্রশিক্ষণ ড্যাশবোর্ডে স্বাগতম'
    },

    /* ================= TAGALOG ================= */
    tl: {
        // Shared
        welcome: 'MALIGAYANG PAGBALIK',
        safetyAlert: 'BABALA SA KALIGTASAN: SIGURADUHING NAKASUOT ANG LAHAT NG KAILANGANG PPE BAGO UMALIS',
        profile: 'PROFILE NG USER',
        langLabel: 'Wika',
        logout: 'MAG-LOG OUT',
        // Login Page
        login: 'MAG-LOGIN',
        signup: 'MAG-SIGN UP',
        empNum: 'Numero ng Empleyado',
        empName: 'Pangalan',
        mobile: 'Numero ng Mobile',
        depot: 'Depot',
        pass: 'Password',
        confirmPass: 'Kumpirmahin ang Password',
        forgot: 'Nakalimutan ang Password?',
        btnLogin: 'SIMULAN ANG PAGSASANAY',
        btnSignup: 'GUMAWA NG ACCOUNT',
        error: 'MALING IMPORMASYON',
        // Password Change
        changePassLink: 'Palitan ang Password',
        oldPass: 'Lumang Password',
        newPass: 'Bagong Password',
        rePass: 'I-type muli ang Bagong Password',
        btnChange: 'PALITAN',
        btnBack: 'BUMALIK',
        passSuccess: 'Matagumpay na na-update ang Password',
        passError: 'Error: Suriin ang Lumang Password',
        passMismatch: 'Hindi magkapareho ang bagong password',
        // Dashboard & Player
        pending: 'MGA NAKABINBING GAWAIN',
        completed: 'MGA NAKUMPLETONG MODULE',
        training: 'Pagsasanay',
        assessment: 'Pagsusuri',
        score: 'Iskor',
        completedDate: 'Napatunayan noong:',
        next: 'SUNOD',
        prev: 'NAKARAAN',
        finish: 'TAPUSIN ANG MODULE',
        // Loading States (NEW)
        loadingTraining: 'NAGLO-LOAD ANG PAGSASANAY...',
        loadingTest: 'NAGLO-LOAD ANG PAGSUSULIT...',
        ready: 'HANDA',
        // NEW KEYS (Login & Instructions)
        lblId: 'Employee ID / Qatar ID',
        instrTitle: 'Mga Tagubilin:',
        instrStaffTitle: 'Mowasalat Staff:',
        instrStaffText: 'Ilagay ang Staff No / Employee ID',
        instrOthersTitle: 'Iba pa:',
        instrOthersText: 'Ilagay ang Qatar ID, Passport No, o Visa No',
        phCompany: 'Kumpanya',
        companyInstr: 'Pakilagay ang pangalan ng iyong kumpanya.',
        phDesignation: 'Posisyon / Team',
        phDepot: 'Pumili ng Lokasyon',
        phCustomDesignation: 'Ilagay ang Posisyon / Team',
        alertAccountCreated: 'Nagawa ang Account! Mag-login muna.',
        errMissingFields: 'Pakipunan ang lahat ng kinakailangang field.',
        errPassMismatch: 'Hindi magkatugma ang mga password.',
        errRegistrationFailed: 'Hindi nagtagumpay ang pagpaparehistro', // Fallback
        btnWait: 'MAGHINTAY...',
        phEmail: 'Email Address',
        phAssignedArea: 'Assigned Area',
        phSelectCompany: 'Pumili ng Kumpanya',
        phOthersSpecify: 'Iba pa (Tukuyin)',
        phEnterCompanyName: 'Ilagay ang Pangalan ng Kumpanya',

        // New Audited Keys (Internationalization)
        selectLanguage: 'PUMILI NG WIKA',
        languageSelection: 'Pagpili ng Wika',
        selectLanguageToContinue: 'Mangyaring pumili ng wika upang magpatuloy',
        secureConnection: 'Ligtas na Koneksyon',
        loginSuccessful: 'Matagumpay ang Pag-login',
        redirecting: 'Inililipat...',
        plzLoginDashboard: 'Mangyaring mag-log in upang ma-access ang iyong dashboard',
        cancel: 'Kanselahin',
        contactSupport: 'Makipag-ugnayan sa Support',
        hsseModules: 'Mga Module ng Pagsasanay',
        noPendingTraining: 'Walang nakabinbing pagsasanay',
        noCompletedHistory: 'Walang nakumpletong kasaysayan',
        inProgress: 'Kasalukuyang Ginagawa',
        notStarted: 'Hindi pa Nagsisimula',
        attemptFailed: 'Nabigo ang Pagsubok',
        edit: 'I-edit',
        signOut: 'Mag-sign Out',
        update: 'I-update',
        saving: 'Ino-on-save...',
        updating: 'Nag-a-update...',
        welcomeDashboard: 'Maligayang pagdating sa iyong Training Dashboard'
    },

    /* ================= NEPALI ================= */
    ne: {
        // Shared
        welcome: 'पुनः स्वागत छ',
        safetyAlert: 'सुरक्षा सूचना: प्रस्थान गर्नु अघि सबै आवश्यक PPE लगाएको सुनिश्चित गर्नुहोस्',
        profile: 'प्रयोगकर्ता प्रोफाइल',
        langLabel: 'भाषा',
        logout: 'लग आउट',
        // Login Page
        login: 'लग इन',
        signup: 'दर्ता',
        empNum: 'कर्मचारी नम्बर',
        empName: 'नाम',
        mobile: 'मोबाइल नम्बर',
        depot: 'डिपो',
        pass: 'पासवर्ड',
        confirmPass: 'पासवर्ड पुष्टि गर्नुहोस्',
        forgot: 'पासवर्ड बिर्सनुभयो?',
        btnLogin: 'तालिम सुरु गर्नुहोस्',
        btnSignup: 'खाता बनाउनुहोस्',
        error: 'गलत विवरण',
        // Password Change
        changePassLink: 'पासवर्ड परिवर्तन गर्नुहोस्',
        oldPass: 'पुरानो पासवर्ड',
        newPass: 'नयाँ पासवर्ड',
        rePass: 'नयाँ पासवर्ड फेरि लेख्नुहोस्',
        btnChange: 'परिवर्तन',
        btnBack: 'फिर्ता',
        passSuccess: 'पासवर्ड सफलतापूर्वक अपडेट भयो',
        passError: 'त्रुटि: पुरानो पासवर्ड जाँच गर्नुहोस्',
        passMismatch: 'नयाँ पासवर्ड मिलेन',
        // Dashboard & Player
        pending: 'बाँकी कार्यहरू',
        completed: 'पूरा भएका मोड्युलहरू',
        training: 'तालिम',
        assessment: 'मूल्यांकन',
        score: 'अंक',
        completedDate: 'प्रमाणित मिति:',
        next: 'अर्को',
        prev: 'अघिल्लो',
        finish: 'मोड्युल समाप्त गर्नुहोस्',
        // Loading States (NEW)
        loadingTraining: 'तालिम लोड हुँदैछ...',
        loadingTest: 'परीक्षा लोड हुँदैछ...',
        ready: 'तयार',
        // NEW KEYS (Login & Instructions)
        lblId: 'कर्मचारी आईडी / कतर आईडी',
        instrTitle: 'निर्देशन:',
        instrStaffTitle: 'मवासलात स्टाफ:',
        instrStaffText: 'स्टाफ नम्बर / कर्मचारी आईडी लेख्नुहोस्',
        instrOthersTitle: 'अन्य:',
        instrOthersText: 'कतर आईडी, पासपोर्ट नं, वा भिसा नं लेख्नुहोस्',
        phCompany: 'कम्पनी',
        companyInstr: 'कृपया आफ्नो कम्पनीको नाम लेख्नुहोस्।',
        phDesignation: 'पद / टिम',
        phDepot: 'स्थान छान्नुहोस्',
        phCustomDesignation: 'पद / टिम लेख्नुहोस्',
        alertAccountCreated: 'खाता बन्यो! कृपया लग इन गर्नुहोस्।',
        errMissingFields: 'कृपया सबै आवश्यक विवरणहरू भर्नुहोस्।',
        errPassMismatch: 'पासवर्डहरू मिलेनन्।',
        errRegistrationFailed: 'दर्ता असफल भयो', // Fallback
        btnWait: 'कृपया पर्खनुहोस्...',
        phEmail: 'इमेल ठेगाना',
        phAssignedArea: 'निर्धारित क्षेत्र',
        phSelectCompany: 'कम्पनी छान्नुहोस्',
        phOthersSpecify: 'अन्य (उल्लेख गर्नुहोस्)',
        phEnterCompanyName: 'कम्पनीको नाम लेख्नुहोस्',

        // New Audited Keys (Internationalization)
        selectLanguage: 'भाषा चयन गर्नुहोस्',
        languageSelection: 'भाषा चयन',
        selectLanguageToContinue: 'अगाडि बढ्नका लागि कृपया एउटा भाषा चयन गर्नुहोस्',
        secureConnection: 'सुरक्षित जडान',
        loginSuccessful: 'लगइन सफल',
        redirecting: 'पुनर्निर्देशित हुँदैछ...',
        plzLoginDashboard: 'आफ्नो ड्यासबोर्डमा पहुँच गर्न कृपया लगइन गर्नुहोस्',
        cancel: 'रद्द गर्नुहोस्',
        contactSupport: 'सपोर्टमा सम्पर्क गर्नुहोस्',
        hsseModules: 'प्रशिक्षण मोड्युलहरू',
        noPendingTraining: 'कुनै बाँकी तालिम छैन',
        noCompletedHistory: 'कुनै पूरा भएको इतिहास छैन',
        inProgress: 'प्रगतिमा छ',
        notStarted: 'सुरु भएको छैन',
        attemptFailed: 'प्रयास असफल भयो',
        edit: 'सम्पादन गर्नुहोस्',
        signOut: 'लग आउट गर्नुहोस्',
        update: 'अपडेट गर्नुहोस्',
        saving: 'बचत गर्दै...',
        updating: 'अपडेट गर्दै...',
        welcomeDashboard: 'तपाईंको प्रशिक्षण ड्यासबोर्डमा स्वागत छ'
    },

    /* ================= MALAYALAM ================= */
    ml: {
        // Shared
        welcome: 'വീണ്ടും സ്വാഗതം',
        safetyAlert: 'സുരക്ഷാ മുന്നറിയിപ്പ്: പുറപ്പെടുന്നതിന് മുമ്പ് ആവശ്യമായ എല്ലാ PPEയും ധരിച്ചിട്ടുണ്ടെന്ന് ഉറപ്പാക്കുക',
        profile: 'ഉപയോക്തൃ പ്രൊഫൈൽ',
        langLabel: 'ഭാഷ',
        logout: 'ലോഗ് ഔട്ട്',
        // Login Page
        login: 'ലോഗിൻ',
        signup: 'രജിസ്റ്റർ',
        empNum: 'ജീവനക്കാരൻ നമ്പർ',
        empName: 'പേര്',
        mobile: 'മൊബൈൽ നമ്പർ',
        depot: 'ഡിപ്പോ',
        pass: 'പാസ്‌വേഡ്',
        confirmPass: 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
        forgot: 'പാസ്‌വേഡ് മറന്നോ?',
        btnLogin: 'പരിശീലനം ആരംഭിക്കുക',
        btnSignup: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
        error: 'തെറ്റായ വിവരങ്ങൾ',
        // Password Change
        changePassLink: 'പാസ്‌വേഡ് മാറ്റുക',
        oldPass: 'പഴയ പാസ്‌വേഡ്',
        newPass: 'പുതിയ പാസ്‌വേഡ്',
        rePass: 'പുതിയ പാസ്‌വേഡ് വീണ്ടും നൽകുക',
        btnChange: 'മാറ്റുക',
        btnBack: 'തിരികെ',
        passSuccess: 'പാസ്‌വേഡ് വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്തു',
        passError: 'പിശക്: പഴയ പാസ്‌വേഡ് പരിശോധിക്കുക',
        passMismatch: 'പുതിയ പാസ്‌വേഡുകൾ ഒത്തുപോകുന്നില്ല',
        // Dashboard & Player
        pending: 'ബാക്കി ജോലികൾ',
        completed: 'പൂർത്തിയായ മോഡ്യൂളുകൾ',
        training: 'പരിശീലനം',
        assessment: 'മൂല്യനിർണ്ണയം',
        score: 'സ്കോർ',
        completedDate: 'സ്ഥിരീകരിച്ച തീയതി:',
        next: 'അടുത്തത്',
        prev: 'മുൻപത്തെത്',
        finish: 'മോഡ്യൂൾ പൂർത്തിയാക്കുക',
        // Loading States (NEW)
        loadingTraining: 'പരിശീലനം ലോഡ് ചെയ്യുന്നു...',
        loadingTest: 'ടെസ്റ്റ് ലോഡ് ചെയ്യുന്നു...',
        ready: 'തയ്യാർ',
        // NEW KEYS (Login & Instructions)
        lblId: 'Employee ID / Qatar ID',
        instrTitle: 'നിർദ്ദേശങ്ങൾ:',
        instrStaffTitle: 'മവാസലാത്ത് സ്റ്റാഫ്:',
        instrStaffText: 'സ്റ്റാഫ് നമ്പർ / എംപ്ലോയി ഐഡി നൽകുക',
        instrOthersTitle: 'മറ്റുള്ളവർ:',
        instrOthersText: 'ഖത്തർ ഐഡി, പാസ്പോർട്ട് നമ്പർ, അല്ലെങ്കിൽ വീസ നമ്പർ നൽകുക',
        phCompany: 'കമ്പനി',
        companyInstr: 'ദയവായി നിങ്ങളുടെ കമ്പനിയുടെ പേര് നൽകുക.',
        phDesignation: 'പദവി / ടീം',
        phDepot: 'ലൊക്കേഷൻ തിരഞ്ഞെടുക്കുക',
        phCustomDesignation: 'പദവി / ടീം നൽകുക',
        alertAccountCreated: 'അക്കൗണ്ട് സൃഷ്ടിച്ചു! ദയവായി ലോഗിൻ ചെയ്യുക.',
        errMissingFields: 'ദയവായി ആവശ്യമായ എല്ലാ വിവരങ്ങളും പൂരിപ്പിക്കുക.',
        errPassMismatch: 'പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല.',
        errRegistrationFailed: 'രജിസ്‌ട്രേഷൻ പരാജയപ്പെട്ടു', // Fallback
        btnWait: 'കാത്തിരിക്കൂ...',
        phEmail: 'ഇമെയിൽ വിലാസം',
        phAssignedArea: 'നിയുക്ത പ്രദേശം',
        phSelectCompany: 'കമ്പനി തിരഞ്ഞെടുക്കുക',
        phOthersSpecify: 'മറ്റുള്ളവ (വ്യക്തമാക്കുക)',
        phEnterCompanyName: 'കമ്പനിയുടെ പേര് നൽകുക',

        // New Audited Keys (Internationalization)
        selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
        languageSelection: 'ഭാഷാ തിരഞ്ഞെടുപ്പ്',
        selectLanguageToContinue: 'തുടരുന്നതിന് ദയവായി ഒരു ഭാഷ തിരഞ്ഞെടുക്കുക',
        secureConnection: 'സുരക്ഷിത കണക്ഷൻ',
        loginSuccessful: 'ലോഗിൻ വിജയിച്ചു',
        redirecting: 'റീഡയറക്ട് ചെയ്യുന്നു...',
        plzLoginDashboard: 'നിങ്ങളുടെ ഡാഷ്‌ബോർഡ് ആക്‌സസ് ചെയ്യുന്നതിന് ദയവായി ലോഗിൻ ചെയ്യുക',
        cancel: 'റദ്ദാക്കുക',
        contactSupport: 'പിന്തുണയുമായി ബന്ധപ്പെടുക',
        hsseModules: 'പരിശീലന മൊഡ്യൂളുകൾ',
        noPendingTraining: 'ബാക്കിയുള്ള പരിശീലനങ്ങളില്ല',
        noCompletedHistory: 'പൂർത്തിയായ ചരിത്രമില്ല',
        inProgress: 'പുരോഗമിക്കുന്നു',
        notStarted: 'ആരംഭിച്ചിട്ടില്ല',
        attemptFailed: 'ശ്രമം പരാജയപ്പെട്ടു',
        edit: 'തിരുത്തുക',
        signOut: 'പുറത്തുകടക്കുക',
        update: 'അപ്‌ഡേറ്റ് ചെയ്യുക',
        saving: 'സേവ് ചെയ്യുന്നു...',
        updating: 'അപ്‌ഡേറ്റ് ചെയ്യുന്നു...',
        welcomeDashboard: 'നിങ്ങളുടെ പരിശീലന ഡാഷ്‌ബോർഡിലേക്ക് സ്വാഗതം'
    },

    /* ================= TAMIL ================= */
    ta: {
        // Shared
        welcome: 'மீண்டும் வரவேற்கிறோம்',
        safetyAlert: 'பாதுகாப்பு எச்சரிக்கை: புறப்படும் முன் தேவையான அனைத்து PPE-யும் அணிந்திருப்பதை உறுதி செய்யவும்',
        profile: 'பயனர் சுயவிவரம்',
        langLabel: 'மொழி',
        logout: 'வெளியேறு',
        // Login Page
        login: 'உள்நுழை',
        signup: 'பதிவு',
        empNum: 'பணியாளர் எண்',
        empName: 'பெயர்',
        mobile: 'மொபைல் எண்',
        depot: 'டிப்போ',
        pass: 'கடவுச்சொல்',
        confirmPass: 'கடவுச்சொல் உறுதி',
        forgot: 'கடவுச்சொல் மறந்துவிட்டதா?',
        btnLogin: 'பயிற்சி தொடங்கு',
        btnSignup: 'கணக்கு உருவாக்கு',
        error: 'தவறான தகவல்',
        // Password Change
        changePassLink: 'கடவுச்சொல்லை மாற்றவும்',
        oldPass: 'பழைய கடவுச்சொல்',
        newPass: 'புதிய கடவுச்சொல்',
        rePass: 'புதிய கடவுச்சொல்லை மீண்டும் உள்ளிடவும்',
        btnChange: 'மாற்று',
        btnBack: 'பின்னால்',
        passSuccess: 'கடவுச்சொல் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
        passError: 'பிழை: பழைய கடவுச்சொல்லை சரிபார்க்கவும்',
        passMismatch: 'புதிய கடவுச்சொற்கள் பொருந்தவில்லை',
        // Dashboard & Player
        pending: 'நிலுவையில் உள்ள பணிகள்',
        completed: 'முடிக்கப்பட்ட தொகுதிகள்',
        training: 'பயிற்சி',
        assessment: 'மதிப்பீடு',
        score: 'மதிப்பெண்',
        completedDate: 'சரிபார்க்கப்பட்ட தேதி:',
        next: 'அடுத்தது',
        prev: 'முந்தையது',
        finish: 'தொகுதியை முடிக்கவும்',
        // Loading States (NEW)
        loadingTraining: 'பயிற்சி ஏற்றப்படுகிறது...',
        loadingTest: 'தேர்வு ஏற்றப்படுகிறது...',
        ready: 'தயார்',
        // NEW KEYS (Login & Instructions)
        lblId: 'பணியாளர் ஐடி / கத்தார் ஐடி',
        instrTitle: 'வழிமுறைகள்:',
        instrStaffTitle: 'மவாசலாத் பணியாளர்கள்:',
        instrStaffText: 'ஸ்டாப் எண் / பணியாளர் ஐடி உள்ளிடவும்',
        instrOthersTitle: 'மற்றவர்கள்:',
        instrOthersText: 'கத்தார் ஐடி, பாஸ்போர்ட் எண், அல்லது விசா எண் உள்ளிடவும்',
        phCompany: 'நிறுவனம்',
        companyInstr: 'உங்கள் நிறுவனத்தின் பெயரை உள்ளிடவும்.',
        phDesignation: 'பதவி / குழு',
        phDepot: 'இடத்தை தேர்வு செய்யவும்',
        phCustomDesignation: 'பதவி / குழுவை உள்ளிடவும்',
        alertAccountCreated: 'கணக்கு உருவாக்கப்பட்டது! தயவுசெய்து உள்நுழையவும்.',
        errMissingFields: 'தேவையான அனைத்து விவரங்களையும் நிரப்பவும்.',
        errPassMismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை.',
        errRegistrationFailed: 'பதிவு தோல்வியடைந்தது', // Fallback
        btnWait: 'காத்திருங்கள்...',
        phEmail: 'மின்னஞ்சல் முகவரி',
        phAssignedArea: 'ஒதுக்கப்பட்ட பகுதி',
        phSelectCompany: 'நிறுவனத்தைத் தேர்ந்தெடுக்கவும்',
        phOthersSpecify: 'மற்றவை (குறிப்பிடவும்)',
        phEnterCompanyName: 'நிறுவனத்தின் பெயரை உள்ளிடவும்',

        // New Audited Keys (Internationalization)
        selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
        languageSelection: 'மொழித் தேர்வு',
        selectLanguageToContinue: 'தொடர தயவுசெய்து ஒரு மொழியைத் தேர்ந்தெடுக்கவும்',
        secureConnection: 'பாதுகாப்பான இணைப்பு',
        loginSuccessful: 'உள்நுழைவு வெற்றி',
        redirecting: 'திசைதிருப்பப்படுகிறது...',
        plzLoginDashboard: 'உங்கள் டாஷ்போர்டை அணுக தயவுசெய்து உள்நுழையவும்',
        cancel: 'ரத்து செய்',
        contactSupport: 'ஆதரவைத் தொடர்பு கொள்ளவும்',
        hsseModules: 'பயிற்சி தொகுதிகள்',
        noPendingTraining: 'நிலுவையில் பயிற்சி இல்லை',
        noCompletedHistory: 'முடிந்த வரலாறு இல்லை',
        inProgress: 'செயல்பாட்டில் உள்ளது',
        notStarted: 'தொடங்கப்படவில்லை',
        attemptFailed: 'முயற்சி தோல்வியடைந்தது',
        edit: 'திருத்து',
        signOut: 'வெளியேறு',
        update: 'புதுப்பி',
        saving: 'சேமிக்கிறது...',
        updating: 'புதுப்பிக்கிறது...',
        welcomeDashboard: 'உங்கள் பயிற்சி டாஷ்போர்டிற்கு வரவேற்கிறோம்'
    },

    /* ================= TELUGU ================= */
    te: {
        // Shared
        welcome: 'మళ్లీ స్వాగతం',
        safetyAlert: 'భద్రతా హెచ్చరిక: బయలుదేరే ముందు అవసరమైన అన్ని PPE ధరించారని నిర్ధారించుకోండి',
        profile: 'వినియోగదారు ప్రొఫైల్',
        langLabel: 'భాష',
        logout: 'లాగ్ అవుట్',
        // Login Page
        login: 'లాగిన్',
        signup: 'నమోదు',
        empNum: 'ఉద్యోగి సంఖ్య',
        empName: 'పేరు',
        mobile: 'మొబైల్ నంబర్',
        depot: 'డిపో',
        pass: 'పాస్‌వర్డ్',
        confirmPass: 'పాస్‌వర్డ్ నిర్ధారించండి',
        forgot: 'పాస్‌వర్డ్ మర్చిపోయారా?',
        btnLogin: 'శిక్షణ ప్రారంభించండి',
        btnSignup: 'ఖాతా సృష్టించండి',
        error: 'తప్పు వివరాలు',
        // Password Change
        changePassLink: 'పాస్‌వర్డ్ మార్చండి',
        oldPass: 'పాత పాస్‌వర్డ్',
        newPass: 'కొత్త పాస్‌వర్డ్',
        rePass: 'కొత్త పాస్‌వర్డ్ మళ్లీ నమోదు చేయండి',
        btnChange: 'మార్చు',
        btnBack: 'వెనక్కి',
        passSuccess: 'పాస్‌వర్డ్ విజయవంతంగా అప్డేట్ అయింది',
        passError: 'లోపం: పాత పాస్‌వర్డ్ తనిఖీ చేయండి',
        passMismatch: 'కొత్త పాస్‌వర్డ్‌లు సరిపోలడం లేదు',
        // Dashboard & Player
        pending: 'పెండింగ్ పనులు',
        completed: 'పూర్తైన మాడ్యూల్స్',
        training: 'శిక్షణ',
        assessment: 'మూల్యాంకనం',
        score: 'స్కోర్',
        completedDate: 'ధృవీకరించిన తేదీ:',
        next: 'తరువాత',
        prev: 'మునుపటి',
        finish: 'మాడ్యూల్ పూర్తి చేయండి',
        // Loading States (NEW)
        loadingTraining: 'శిక్షణ లోడ్ అవుతోంది...',
        loadingTest: 'పరీక్ష లోడ్ అవుతోంది...',
        ready: 'సిద్ధం',
        // NEW KEYS (Login & Instructions)
        lblId: 'ఉద్యోగి ఐడి / కతార్ ఐడి',
        instrTitle: 'సూచనలు:',
        instrStaffTitle: 'మవాసలాత్ స్టాఫ్:',
        instrStaffText: 'స్టాఫ్ నం / ఉద్యోగి ఐడి నమోదు చేయండి',
        instrOthersTitle: 'ఇతరులు:',
        instrOthersText: 'కతార్ ఐడి, పాస్‌పోర్ట్ నం, లేదా వీసా నం నమోదు చేయండి',
        phCompany: 'కంపెనీ',
        companyInstr: 'దయచేసి మీ కంపెనీ పేరు నమోదు చేయండి.',
        phDesignation: 'పదవి / టీమ్',
        phDepot: 'లొకేషన్ ఎంచుకోండి',
        phCustomDesignation: 'పదవి / టీమ్ నమోదు చేయండి',
        alertAccountCreated: 'ఖాతా సృష్టించబడింది! దయచేసి లాగిన్ అవ్వండి.',
        errMissingFields: 'దయచేసి అవసరమైన అన్ని ఫీల్డ్స్ నింపండి.',
        errPassMismatch: 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు.',
        errRegistrationFailed: 'నమోదు విఫలమైంది', // Fallback
        btnWait: 'దయచేసి వేచి ఉండండి...',
        phEmail: 'ఇమెయిల్ అడ్రస్',
        phAssignedArea: 'నిర్దేశించిన ప్రాంతం',
        phSelectCompany: 'కంపెనీని ఎంచుకోండి',
        phOthersSpecify: 'ఇతరాలు (తెలియజేయండి)',
        phEnterCompanyName: 'కంపెనీ పేరు నమోదు చేయండి',

        // New Audited Keys (Internationalization)
        selectLanguage: 'భాషను ఎంచుకోండి',
        languageSelection: 'భాష ఎంపిక',
        selectLanguageToContinue: 'ముందుకు సాగడానికి దయచేసి ఒక భాషను ఎంచుకోండి',
        secureConnection: 'సురక్షిత కనెక్షన్',
        loginSuccessful: 'లాగిన్ విజయవంతమైంది',
        redirecting: 'రీడైరెక్ట్ అవుతోంది...',
        plzLoginDashboard: 'మీ డాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి దయచేసి లాగిన్ చేయండి',
        cancel: 'రద్దు చేయి',
        contactSupport: 'సపోర్ట్‌ను సంప్రదించండి',
        hsseModules: 'శిక్షణ మాడ్యూల్స్',
        noPendingTraining: 'పెండింగ్ శిక్షణ ఏదీ లేదు',
        noCompletedHistory: 'పూర్తయిన చరిత్ర ఏదీ లేదు',
        inProgress: 'పురోగతిలో ఉంది',
        notStarted: 'ప్రారంభించబడలేదు',
        attemptFailed: 'ప్రయత్నం విఫలమైంది',
        edit: 'సవరించు',
        signOut: 'సైన్ అవుట్',
        update: 'నవీకరించు',
        saving: 'సేవ్ అవుతోంది...',
        updating: 'నవీకరించబడుతోంది...',
        welcomeDashboard: 'మీ శిక్షణ డాష్‌బోర్డ్‌కు స్వాగతం'
    },

    /* ================= KANNADA ================= */
    kn: {
        // Shared
        welcome: 'ಮತ್ತೆ ಸ್ವಾಗತ',
        safetyAlert: 'ಭದ್ರತಾ ಎಚ್ಚರಿಕೆ: ಪ್ರಯಾಣಕ್ಕೂ ಮೊದಲು ಅಗತ್ಯವಿರುವ ಎಲ್ಲಾ PPE ಧರಿಸಿರುವುದನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ',
        profile: 'ಬಳಕೆದಾರ ಪ್ರೊಫೈಲ್',
        langLabel: 'ಭಾಷೆ',
        logout: 'ಲಾಗ್ ಔಟ್',
        // Login Page
        login: 'ಲಾಗಿನ್',
        signup: 'ನೋಂದಣಿ',
        empNum: 'ಉದ್ಯೋಗಿ ಸಂಖ್ಯೆ',
        empName: 'ಹೆಸರು',
        mobile: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
        depot: 'ಡಿಪೋ',
        pass: 'ಪಾಸ್‌ವರ್ಡ್',
        confirmPass: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
        forgot: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
        btnLogin: 'ತರಬೇತಿ ಪ್ರಾರಂಭಿಸಿ',
        btnSignup: 'ಖಾತೆ ರಚಿಸಿ',
        error: 'ತಪ್ಪಾದ ಮಾಹಿತಿ',
        // Password Change
        changePassLink: 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಿಸಿ',
        oldPass: 'ಹಳೆಯ ಪಾಸ್‌ವರ್ಡ್',
        newPass: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
        rePass: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತೆ ನಮೂದಿಸಿ',
        btnChange: 'ಬದಲಿಸಿ',
        btnBack: 'ಹಿಂದೆ',
        passSuccess: 'ಪಾಸ್‌ವರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಡೇಟ್ ಆಗಿದೆ',
        passError: 'ದೋಷ: ಹಳೆಯ ಪಾಸ್‌ವರ್ಡ್ ಪರಿಶೀಲಿಸಿ',
        passMismatch: 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
        // Dashboard & Player
        pending: 'ಬಾಕಿ ಇರುವ ಕಾರ್ಯಗಳು',
        completed: 'ಪೂರ್ಣಗೊಂಡ ಮಾಡ್ಯೂಲ್‌ಗಳು',
        training: 'ತರಬೇತಿ',
        assessment: 'ಮೌಲ್ಯಮಾಪನ',
        score: 'ಸ್ಕೋರ್',
        completedDate: 'ದೃಢೀಕರಿಸಿದ ದಿನಾಂಕ:',
        next: 'ಮುಂದೆ',
        prev: 'ಹಿಂದೆ',
        finish: 'ಮಾಡ್ಯೂಲ್ ಮುಗಿಸಿ',
        // Loading States (NEW)
        loadingTraining: 'ತರಬೇತಿ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
        loadingTest: 'ಪರೀಕ್ಷೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
        ready: 'ಸಿದ್ಧ',
        // NEW KEYS (Login & Instructions)
        lblId: 'ಉದ್ಯೋಗಿ ಐಡಿ / ಕತಾರ್ ಐಡಿ',
        instrTitle: 'ಸೂಚನೆಗಳು:',
        instrStaffTitle: 'ಮವಾಸಲಾತ್ ಸಿಬ್ಬಂದಿ:',
        instrStaffText: 'ಸ್ಟಾಫ್ ನಂ / ಉದ್ಯೋಗಿ ಐಡಿ ನಮೂದಿಸಿ',
        instrOthersTitle: 'ಇತರರು:',
        instrOthersText: 'ಕತಾರ್ ಐಡಿ, ಪಾಸ್‌ಪೋರ್ಟ್ ನಂ, ಅಥವಾ ವೀಸಾ ನಂ ನಮೂದಿಸಿ',
        phCompany: 'ಕಂಪನಿ',
        companyInstr: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಕಂಪನಿಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ.',
        phDesignation: 'ಹುದ್ದೆ / ತಂಡ',
        phDepot: 'ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ',
        phCustomDesignation: 'ಹುದ್ದೆ / ತಂಡ ನಮೂದಿಸಿ',
        alertAccountCreated: 'ಖಾತೆ ಸೃಷ್ಟಿಸಲಾಗಿದೆ! ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ.',
        errMissingFields: 'ದಯವಿಟ್ಟು ಅಗತ್ಯವಿರುವ ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ತುಂಬಿ.',
        errPassMismatch: 'ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ.',
        errRegistrationFailed: 'ನೋಂದಣಿ ವಿಫಲವಾಗಿದೆ', // Fallback
        btnWait: 'ದಯವಿಟ್ಟು ಕಾಯಿರಿ...',
        phEmail: 'ಇಮೇಲ್ ವಿಳಾಸ',
        phAssignedArea: 'ನಿಯೋಜಿತ ಪ್ರದೇಶ',
        phSelectCompany: 'ಕಂಪನಿ ಆಯ್ಕೆಮಾಡಿ',
        phOthersSpecify: 'ಇತರೆ (ಸೂಚಿಸಿ)',
        phEnterCompanyName: 'ಕಂಪನಿಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',

        // New Audited Keys (Internationalization)
        selectLanguage: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
        languageSelection: 'ಭಾಷೆ ಆಯ್ಕೆ',
        selectLanguageToContinue: 'ಮುಂದುವರಿಯಲು ದಯವಿಟ್ಟು ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
        secureConnection: 'ಸುರಕ್ಷಿತ ಸಂಪರ್ಕ',
        loginSuccessful: 'ಲಾಗಿನ್ ಯಶಸ್ವಿಯಾಗಿದೆ',
        redirecting: 'ಮರುನಿರ್ದೇಶಿಸಲಾಗುತ್ತಿದೆ...',
        plzLoginDashboard: 'ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಿಸಲು ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ',
        cancel: 'ರದ್ದುಮಾಡಿ',
        contactSupport: 'ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ',
        hsseModules: 'ತರಬೇತಿ ಮಾಡ್ಯೂಲ್‌ಗಳು',
        noPendingTraining: 'ಯಾವುದೇ ಬಾಕಿ ತರಬೇತಿ ಇಲ್ಲ',
        noCompletedHistory: 'ಯಾವುದೇ ಪೂರ್ಣಗೊಂಡ ಇತಿಹಾಸವಿಲ್ಲ',
        inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
        notStarted: 'ಪ್ರಾರಂಭವಾಗಿಲ್ಲ',
        attemptFailed: 'ಪ್ರಯತ್ನ ವಿಫಲವಾಗಿದೆ',
        edit: 'ಸಂಪಾದಿಸಿ',
        signOut: 'ಸೈನ್ ಔಟ್',
        update: 'ಅಪ್ಡೇಟ್ ಮಾಡಿ',
        saving: 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
        updating: 'ಅಪ್ಡೇಟ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
        welcomeDashboard: 'ನಿಮ್ಮ ತರಬೇತಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಸ್ವಾಗತ'
    },

    /* ================= ODIA ================= */
    or: {
        // Shared
        welcome: 'ପୁନର୍ବାର ସ୍ୱାଗତ',
        safetyAlert: 'ସୁରକ୍ଷା ସତର୍କତା: ଯାତ୍ରା ପୂର୍ବରୁ ସମସ୍ତ ଆବଶ୍ୟକ PPE ପିନ୍ଧିଥିବା ନିଶ୍ଚିତ କରନ୍ତୁ',
        profile: 'ଉପଯୋଗକର୍ତ୍ତା ପ୍ରୋଫାଇଲ୍',
        langLabel: 'ଭାଷା',
        logout: 'ଲଗ୍ଆଉଟ୍',
        // Login Page
        login: 'ଲଗ୍ଇନ୍',
        signup: 'ପଞ୍ଜିକରଣ',
        empNum: 'କର୍ମଚାରୀ ସଂଖ୍ୟା',
        empName: 'ନାମ',
        mobile: 'ମୋବାଇଲ୍ ନମ୍ବର',
        depot: 'ଡିପୋ',
        pass: 'ପାସୱାର୍ଡ',
        confirmPass: 'ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ',
        forgot: 'ପାସୱାର୍ଡ ଭୁଲିଗଲେ?',
        btnLogin: 'ଟ୍ରେନିଂ ଆରମ୍ଭ କରନ୍ତୁ',
        btnSignup: 'ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ',
        error: 'ଭୁଲ୍ ବିବରଣୀ',
        // Password Change
        changePassLink: 'ପାସୱାର୍ଡ ପରିବର୍ତ୍ତନ କରନ୍ତୁ',
        oldPass: 'ପୁରୁଣା ପାସୱାର୍ଡ',
        newPass: 'ନୂତନ ପାସୱାର୍ଡ',
        rePass: 'ନୂତନ ପାସୱାର୍ଡ ପୁନର୍ବାର ଲେଖନ୍ତୁ',
        btnChange: 'ପରିବର୍ତ୍ତନ କରନ୍ତୁ',
        btnBack: 'ଫେରିଯାଆନ୍ତୁ',
        passSuccess: 'ପାସୱାର୍ଡ ସଫଳତାର ସହ ଅପଡେଟ୍ ହେଲା',
        passError: 'ତ୍ରୁଟି: ପୁରୁଣା ପାସୱାର୍ଡ ଯାଞ୍ଚ କରନ୍ତୁ',
        passMismatch: 'ନୂତନ ପାସୱାର୍ଡ ମେଳ ଖାଉନାହିଁ',
        // Dashboard & Player
        pending: 'ବାକି ଥିବା କାର୍ଯ୍ୟ',
        completed: 'ସମ୍ପୂର୍ଣ୍ଣ ହୋଇଥିବା ମଡ୍ୟୁଲ୍',
        training: 'ଟ୍ରେନିଂ',
        assessment: 'ମୂଲ୍ୟାଙ୍କନ',
        score: 'ସ୍କୋର',
        completedDate: 'ଯାଞ୍ଚ ତାରିଖ:',
        next: 'ପରବର୍ତ୍ତୀ',
        prev: 'ପୂର୍ବବର୍ତ୍ତୀ',
        finish: 'ମଡ୍ୟୁଲ୍ ସମାପ୍ତ କରନ୍ତୁ',
        // Loading States (NEW)
        loadingTraining: 'ଟ୍ରେନିଂ ଲୋଡ୍ ହେଉଛି...',
        loadingTest: 'ପରୀକ୍ଷା ଲୋଡ୍ ହେଉଛି...',
        ready: 'ପ୍ରସ୍ତୁତ',
        // NEW KEYS (Login & Instructions)
        lblId: 'କର୍ମଚାରୀ ଆଇଡି / କତାର ଆଇଡି',
        instrTitle: 'ନିର୍ଦ୍ଦେଶାବଳୀ:',
        instrStaffTitle: 'ମୱାସାଲାତ୍ ଷ୍ଟାଫ୍:',
        instrStaffText: 'ଷ୍ଟାଫ୍ ନମ୍ବର / କର୍ମଚାରୀ ଆଇଡି ଲେଖନ୍ତୁ',
        instrOthersTitle: 'ଅନ୍ୟାନ୍ୟ:',
        instrOthersText: 'କତାର ଆଇଡି, ପାସପୋର୍ଟ ନମ୍ବର, କିମ୍ବା ଭିସା ନମ୍ବର ଲେଖନ୍ତୁ',
        phCompany: 'କମ୍ପାନୀ',
        companyInstr: 'ଦୟାକରି ଆପଣଙ୍କ କମ୍ପାନୀ ନାମ ଲେଖନ୍ତୁ।',
        phDesignation: 'ପଦବୀ / ଟିମ୍',
        phDepot: 'ସ୍ଥାନ ଚୟନ କରନ୍ତୁ',
        phCustomDesignation: 'ପଦବୀ / ଟିମ୍ ଲେଖନ୍ତୁ',
        alertAccountCreated: 'ଆକାଉଣ୍ଟ୍ ତିଆରି ହୋଇଗଲା! ଦୟାକରି ଲଗ୍ଇନ୍ କରନ୍ତୁ।',
        errMissingFields: 'ଦୟାକରି ସମସ୍ତ ଆବଶ୍ୟକୀୟ ତଥ୍ୟ ପୂରଣ କରନ୍ତୁ।',
        errPassMismatch: 'ପାସୱାର୍ଡ ମେଳ ଖାଉନାହିଁ।',
        errRegistrationFailed: 'ପଞ୍ଜିକରଣ ବିଫଳ ହେଲା', // Fallback
        btnWait: 'ଅପେକ୍ଷା କରନ୍ତୁ...',
        phEmail: 'ଇମେଲ ଠିକଣା',
        phAssignedArea: 'ନିର୍ଦ୍ଧାରିତ ଅଞ୍ଚଳ',
        phSelectCompany: 'କମ୍ପାନୀ ଚୟନ କରନ୍ତୁ',
        phOthersSpecify: 'ଅନ୍ୟାନ୍ୟ (ଉଲ୍ଲେଖ କରନ୍ତୁ)',
        phEnterCompanyName: 'କମ୍ପାନୀ ନାମ ପ୍ରବେଶ କରନ୍ତୁ',

        // New Audited Keys (Internationalization)
        selectLanguage: 'ଭାଷା ଚୟନ କରନ୍ତୁ',
        languageSelection: 'ଭାଷା ଚୟନ',
        selectLanguageToContinue: 'ଆଗକୁ ବଢିବା ପାଇଁ ଦୟାକରି ଏକ ଭାଷା ଚୟନ କରନ୍ତୁ',
        secureConnection: 'ସୁରକ୍ଷିତ ସଂଯୋଗ',
        loginSuccessful: 'ଲଗଇନ୍ ସଫଳ ହେଲା',
        redirecting: 'ପୁନର୍ନିଦ୍ଦେଶିତ ହେଉଛି...',
        plzLoginDashboard: 'ଆପଣଙ୍କର ଡ୍ୟାସବୋର୍ଡକୁ ପ୍ରବେଶ କରିବା ପାଇଁ ଦୟାକରି ଲଗଇନ୍ କରନ୍ତୁ',
        cancel: 'ବାତିଲ କରନ୍ତୁ',
        contactSupport: 'ସହାୟତା ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ',
        hsseModules: 'ଟ୍ରେନିଂ ମଡ୍ୟୁଲ୍',
        noPendingTraining: 'କୌଣସି ବାକି ତାଲିମ ନାହିଁ',
        noCompletedHistory: 'କୌଣସି ସମ୍ପୂର୍ଣ୍ଣ ଇତିହାସ ନାହିଁ',
        inProgress: 'ଚାଲୁ ରହିଛି',
        notStarted: 'ଆରମ୍ଭ ହୋଇନାହିଁ',
        attemptFailed: 'ପ୍ରୟାସ ବିଫଳ ହେଲା',
        edit: 'ସଂପାଦନ କରନ୍ତୁ',
        signOut: 'ସାଇନ୍ ଆଉଟ୍',
        update: 'ଅପଡେଟ୍ କରନ୍ତୁ',
        saving: 'ସଂରକ୍ଷଣ କରାଯାଉଛି...',
        updating: 'ଅପଡେଟ୍ କରାଯାଉଛି...',
        welcomeDashboard: 'ଆପଣଙ୍କର ପ୍ରଶିକ୍ଷଣ ଡ୍ୟାସବୋର୍ଡକୁ ସ୍ୱାଗତ'
    },

    /* ================= SINHALA ================= */
    si: {
        // Shared
        welcome: 'නැවත සාදරයෙන් පිළිගනිමු',
        safetyAlert: 'ආරක්ෂක අනතුරු ඇඟවීම: පිටත්වීමට පෙර අවශ්‍ය සියලුම PPE පැළඳ ඇති බව තහවුරු කරගන්න',
        profile: 'පරිශීලක පැතිකඩ',
        langLabel: 'භාෂාව',
        logout: 'ඉවත් වන්න',
        // Login Page
        login: 'ඇතුල් වන්න',
        signup: 'ලියාපදිංචි වන්න',
        empNum: 'සේවක අංකය',
        empName: 'නම',
        mobile: 'ජංගම දුරකථන අංකය',
        depot: 'ඩිපෝව',
        pass: 'මුරපදය',
        confirmPass: 'මුරපදය තහවුරු කරන්න',
        forgot: 'මුරපදය අමතකද?',
        btnLogin: 'පුහුණුව ආරම්භ කරන්න',
        btnSignup: 'ගිණුමක් සාදන්න',
        error: 'වැරදි තොරතුරු',
        // Password Change
        changePassLink: 'මුරපදය වෙනස් කරන්න',
        oldPass: 'පැරණි මුරපදය',
        newPass: 'නව මුරපදය',
        rePass: 'නව මුරපදය නැවත ඇතුළත් කරන්න',
        btnChange: 'වෙනස් කරන්න',
        btnBack: 'ආපසු',
        passSuccess: 'මුරපදය සාර්ථකව යාවත්කාලීන කරන ලදී',
        passError: 'දෝෂය: පැරණි මුරපදය පරීක්ෂා කරන්න',
        passMismatch: 'නව මුරපද නොගැලපේ',
        // Dashboard & Player
        pending: 'වෙමින් පවතින කාර්යයන්',
        completed: 'සම්පූර්ණ කරන ලද මොඩියුල',
        training: 'පුහුණුව',
        assessment: 'ඇගයීම',
        score: 'ලකුණු',
        completedDate: 'තහවුරු කළ දිනය:',
        next: 'ඊළඟ',
        prev: 'පෙර',
        finish: 'මොඩියුලය අවසන් කරන්න',
        // Loading States (NEW)
        loadingTraining: 'පුහුණුව පටවමින් පවතී...',
        loadingTest: 'පරීක්ෂණය පටවමින් පවතී...',
        ready: 'සූදානම්',
        // NEW KEYS (Login & Instructions)
        lblId: 'සේවක අංකය / කටාර් හැඳුනුම්පත',
        instrTitle: 'උපදෙස්:',
        instrStaffTitle: 'මවාසලත් කාර්ය මණ්ඩලය:',
        instrStaffText: 'කාර්ය මණ්ඩල අංකය / සේවක අංකය ඇතුළත් කරන්න',
        instrOthersTitle: 'වෙනත්:',
        instrOthersText: 'කටාර් හැඳුනුම්පත, විදේශ ගමන් බලපත්‍ර අංකය, හෝ වීසා අංකය ඇතුළත් කරන්න',
        phCompany: 'ආයතනය',
        companyInstr: 'කරුණාකර ඔබේ ආයතනයේ නම ඇතුළත් කරන්න.',
        phDesignation: 'තනතුර / කණ්ඩායම',
        phDepot: 'ස්ථානය තෝරන්න',
        phCustomDesignation: 'තනතුර / කණ්ඩායම ඇතුළත් කරන්න',
        alertAccountCreated: 'ගිණුම සාදන ලදී! කරුණාකර ඇතුල් වන්න.',
        errMissingFields: 'කරුණාකර අවශ්‍ය සියලුම ක්ෂේත්‍ර පුරවන්න.',
        errPassMismatch: 'මුරපද නොගැලපේ.',
        errRegistrationFailed: 'ලියාපදිංචිය අසාර්ථකයි', // Fallback
        btnWait: 'රැදී සිටින්න...',
        phEmail: 'විද්යුත් තැපැල් ලිපිනය',
        phAssignedArea: 'පවරා ඇති ප්‍රදේශය',
        phSelectCompany: 'ආයතනය තෝරන්න',
        phOthersSpecify: 'වෙනත් (සඳහන් කරන්න)',
        phEnterCompanyName: 'සමාගමේ නම ඇතුළත් කරන්න',

        // New Audited Keys (Internationalization)
        selectLanguage: 'භාෂාව තෝරන්න',
        languageSelection: 'භාෂාව තෝරා ගැනීම',
        selectLanguageToContinue: 'ඉදිරියට යාමට කරුණාකර භාෂාවක් තෝරන්න',
        secureConnection: 'ආරක්ෂිත සම්බන්ධතාවය',
        loginSuccessful: 'ඇතුල්වීම සාර්ථකයි',
        redirecting: 'යොමු වෙමින් පවතී...',
        plzLoginDashboard: 'ඔබගේ උපකරණ පුවරුවට ප්‍රවේශ වීමට කරුණාකර ඇතුළු වන්න',
        cancel: 'අවලංගු කරන්න',
        contactSupport: 'සහාය අමතන්න',
        hsseModules: 'පුහුණු මොඩියුල',
        noPendingTraining: 'පොරොත්තු පුහුණු නොමැත',
        noCompletedHistory: 'සම්පූර්ණ ඉතිහාසයක් නොමැත',
        inProgress: 'සිදුවෙමින් පවතී',
        notStarted: 'ආරම්භ කර නැත',
        attemptFailed: 'උත්සාහය අසාර්ථකයි',
        edit: 'සංස්කරණය',
        signOut: 'ඉවත් වන්න',
        update: 'යාවත්කාලීන කරන්න',
        saving: 'සුරකිමින්...',
        updating: 'යාවත්කාලීන වෙමින්...',
        welcomeDashboard: 'ඔබගේ පුහුණු උපකරණ පුවරුව වෙත සාදරයෙන් පිළිගනිමු'
    },

    /* ================= PASHTO ================= */
    ps: {
        // Shared
        welcome: 'ښه راغلاست',
        safetyAlert: 'د خوندیتوب خبرتیا: مهرباني وکړئ د تګ دمخه ډاډ ترلاسه کړئ چې ټول اړین PPE اغوستل شوي دي',
        profile: 'د کارونکي پېژندڅېره',
        langLabel: 'ژبه',
        logout: 'وتل',
        // Login Page
        login: 'ننوتل',
        signup: 'راجسټر',
        empNum: 'د کارمند شمېره',
        empName: 'نوم',
        mobile: 'د موبایل شمېره',
        depot: 'ډیپو',
        pass: 'پټنوم',
        confirmPass: 'پټنوم تایید کړئ',
        forgot: 'پټنوم مو هیر شوی؟',
        btnLogin: 'روزنه پیل کړئ',
        btnSignup: 'اکاونټ جوړ کړئ',
        error: 'ناسم معلومات',
        // Password Change
        changePassLink: 'پټنوم بدل کړئ',
        oldPass: 'زوړ پټنوم',
        newPass: 'وی پټنوم',
        rePass: 'وی پټنوم بیا دننه کړئ',
        btnChange: 'بدل کړئ',
        btnBack: 'شاته',
        passSuccess: 'پټنوم په بریالیتوب سره تازه شو',
        passError: 'تېروتنه: زوړ پټنوم چیک کړئ',
        passMismatch: 'نوي پټنومونه سره سمون نه خوري',
        // Dashboard & Player
        pending: 'پاتې کارونه',
        completed: 'بشپړ شوي ماډلونه',
        training: 'روزنه',
        assessment: 'ارزونه',
        score: 'نمرې',
        completedDate: 'تایید شوې نېټه:',
        next: 'بل',
        prev: 'پخوانی',
        finish: 'ماډل پای ته ورسوئ',
        // Loading States (NEW)
        loadingTraining: 'روزنه پورته کیږي...',
        loadingTest: 'ازموینه پورته کیږي...',
        ready: 'چمتو',
        // NEW KEYS (Login & Instructions)
        lblId: 'د کارمند ID / قطر ID',
        instrTitle: 'لارښوونې:',
        instrStaffTitle: 'د مواصلات کارمندان:',
        instrStaffText: 'د کارمند شمېره / کارمند ID دننه کړئ',
        instrOthersTitle: 'نور:',
        instrOthersText: 'د قطر ID، پاسپورټ شمېره، یا ویزې شمېره دننه کړئ',
        phCompany: 'شرکت',
        companyInstr: 'مهرباني وکړئ د خپل شرکت نوم دننه کړئ.',
        phDesignation: 'دنده / ډله',
        phDepot: 'ځای وټاکئ',
        phCustomDesignation: 'دنده / ډله دننه کړئ',
        alertAccountCreated: 'اکاونټ جوړ شو! مهرباني وکړئ ننوتل وکړئ.',
        errMissingFields: 'مهرباني وکړئ ټول اړین ځایونه ډک کړئ.',
        errPassMismatch: 'پټنومونه سره سمون نه خوري.',
        errRegistrationFailed: 'راجسټر ناکام شو', // Fallback
        btnWait: 'مهرباني وکړئ انتظار وکړئ...',
        phEmail: 'بریښنالیک پته',
        phAssignedArea: 'ټاکل شوې سیمه',
        phSelectCompany: 'شرکت وټاکئ',
        phOthersSpecify: 'نور (مشخص کړئ)',
        phEnterCompanyName: 'د شرکت نوم داخل کړئ',

        // New Audited Keys (Internationalization)
        selectLanguage: 'ژبه انتخاب کړئ',
        languageSelection: 'د ژبې انتخاب',
        selectLanguageToContinue: 'مهرباني وکړئ د دوام لپاره یوه ژبه انتخاب کړئ',
        secureConnection: 'خوندي اړیکه',
        loginSuccessful: 'لاګ ان بریالی شو',
        redirecting: 'بیا لیږل کیږي...',
        plzLoginDashboard: 'مهرباني وکړئ خپل ډشبورډ ته د لاسرسي لپاره لاګ ان شئ',
        cancel: 'لغوه کول',
        contactSupport: 'د ملاتړ سره اړیکه ونیسئ',
        hsseModules: 'د روزنې ماډیولونه',
        noPendingTraining: 'هیڅ پاتې روزنه نشته',
        noCompletedHistory: 'هیڅ بشپړ شوی تاریخ نشته',
        inProgress: 'روان دی',
        notStarted: 'شروع شوی نه دی',
        attemptFailed: 'هڅه ناکامه شوه',
        edit: 'ایډیټ کول',
        signOut: 'وتل',
        update: 'اپډیټ کول',
        saving: 'خوندي کیږي...',
        updating: 'اپډیټ کیږي...',
        welcomeDashboard: 'ستاسو د روزنې ڈشبورډ ته ښه راغلاست'
    },

    /* ================= ROMANIAN ================= */
    ro: {
        // Shared
        welcome: 'BINE AI REVENIT',
        safetyAlert: 'Alertă de siguranță: Vă rugăm să vă asigurați că purtați tot EIP necesar înainte de plecare',
        profile: 'PROFIL UTILIZATOR',
        langLabel: 'Limbă',
        logout: 'DECONECTARE',
        // Login Page
        login: 'AUTENTIFICARE',
        signup: 'ÎNSCRIERE',
        empNum: 'Număr Angajat',
        empName: 'Nume',
        mobile: 'Număr Mobil',
        depot: 'Depou',
        pass: 'Parolă',
        confirmPass: 'Confirmă Parola',
        forgot: 'Ai uitat parola?',
        btnLogin: 'ÎNCEPE INSTRUIREA',
        btnSignup: 'CREEAZĂ CONT',
        error: 'CREDENTIALE INVALIDE',
        // Password Change
        changePassLink: 'Schimbă Parola',
        oldPass: 'Parola Veche',
        newPass: 'Parola Nouă',
        rePass: 'Re-introdu Parola Nouă',
        btnChange: 'SCHIMBĂ',
        btnBack: 'ÎNAPOI',
        passSuccess: 'Parola a fost actualizată cu succes',
        passError: 'Eroare: Verifică Parola Veche',
        passMismatch: 'Parolele noi nu se potrivesc',
        // Dashboard & Player
        pending: 'ARCINE ÎN AȘTEPTARE',
        completed: 'MODULE FINALIZATE',
        training: 'Instruire',
        assessment: 'Evaluare',
        score: 'Scor',
        completedDate: 'Validat pe:',
        next: 'URMĂTORUL',
        prev: 'ANTERIOR',
        finish: 'FINALIZEAZĂ MODULUL',
        // Loading States (NEW)
        loadingTraining: 'SE ÎNCARCĂ INSTRUIREA...',
        loadingTest: 'SE ÎNCARCĂ TESTUL...',
        ready: 'GATA',
        // NEW KEYS (Login & Instructions)
        lblId: 'ID Angajat / QID',
        instrTitle: 'Instrucțiuni:',
        instrStaffTitle: 'Personal Mowasalat:',
        instrStaffText: 'Introduceți Nr. Personal / ID Angajat',
        instrOthersTitle: 'Alții:',
        instrOthersText: 'Introduceți QID, Nr. Pașaport sau Nr. Viză',
        phCompany: 'Companie',
        companyInstr: 'Vă rugăm să introduceți numele companiei dvs.',
        phDesignation: 'Funcție / Echipă',
        phDepot: 'Selectați Locația',
        phCustomDesignation: 'Introduceți Funcția / Echipa',
        alertAccountCreated: 'Cont creat! Vă rugăm să vă autentificați.',
        errMissingFields: 'Vă rugăm să completați toate câmpurile necesare.',
        errPassMismatch: 'Parolele nu se potrivesc.',
        errRegistrationFailed: 'Înregistrarea a eșuat', // Fallback
        btnWait: 'Vă rugăm așteptați...',
        phEmail: 'Adresă de Email',
        phAssignedArea: 'Zona Alocată',
        phSelectCompany: 'Selectați Compania',
        phOthersSpecify: 'Altele (Specificați)',
        phEnterCompanyName: 'Introduceți numele companiei',

        // New Audited Keys (Internationalization)
        selectLanguage: 'SELECTAȚI LIMBA',
        languageSelection: 'Selectarea Limbii',
        selectLanguageToContinue: 'Vă rugăm să selectați o limbă pentru a continua',
        secureConnection: 'Conexiune Securizată',
        loginSuccessful: 'Autentificare Reușită',
        redirecting: 'Redirecționare...',
        plzLoginDashboard: 'Vă rugăm să vă autentificați pentru a accesa tabloul de bord',
        cancel: 'Anulare',
        contactSupport: 'Contactați Suportul',
        hsseModules: 'Module de Instruire',
        noPendingTraining: 'Nu există instruiri în așteptare',
        noCompletedHistory: 'Nu există istoric completat',
        inProgress: 'În Curs',
        notStarted: 'Neînceput',
        attemptFailed: 'Tentativă Eșuată',
        edit: 'Editează',
        signOut: 'Deconectare',
        update: 'Actualizează',
        saving: 'Se salvează...',
        updating: 'Se actualizează...',
        welcomeDashboard: 'Bun venit la tabloul tău de bord pentru instruire'
    },
}
